=== mame/xmlparser/samples/document.dtd
<!-- <!DOCTYPE document [ -->

<!ENTITY % coreattrs "id ID #IMPLIED">
<!ENTITY % phrase "em|code">
<!ENTITY % special "link|image">
<!ENTITY % inline "#PCDATA|%phrase;|%special;">
<!ENTITY % block "para|rpara|list|pre|table">
<!ENTITY % flow "%inline;|%block;">

<!ELEMENT document (title,(index|contents|section|%block;)*)>
<!ATTLIST document %coreattrs;>

<!ELEMENT em (%inline;)*>
<!ATTLIST em %coreattrs;>

<!ELEMENT code (%inline;)*>
<!ATTLIST code %coreattrs;>

<!ELEMENT title (%inline;)*>
<!ATTLIST title %coreattrs;>

<!ELEMENT para (%inline;)*>
<!ATTLIST para %coreattrs;>

<!ELEMENT rpara (%inline;)*>
<!ATTLIST rpara %coreattrs;>

<!ELEMENT contents (item)+>
<!ATTLIST contents %coreattrs;>

<!ELEMENT index (link)+>
<!ATTLIST index %coreattrs;>

<!ELEMENT pre (%inline;)*>
<!ATTLIST pre %coreattrs;>

<!ELEMENT section (heading,(%block;|subsection)*)>
<!ATTLIST section %coreattrs;>

<!ELEMENT subsection (heading,(%block;)*)>
<!ATTLIST subsection %coreattrs;>

<!ELEMENT heading (%inline;)*>
<!ATTLIST heading %coreattrs;>

<!ELEMENT link (%inline;)*>
<!ATTLIST link %coreattrs;>
<!ATTLIST link xml:link CDATA #FIXED 'simple'
               href CDATA #REQUIRED>

<!ELEMENT image EMPTY>
<!ATTLIST image %coreattrs;
                xml:link CDATA #FIXED 'simple'
                href CDATA #REQUIRED
                title CDATA #REQUIRED
                role CDATA #IMPLIED
                show CDATA #IMPLIED>

<!ELEMENT list (item)+>
<!ATTLIST list %coreattrs;>

<!ELEMENT item (%flow;)*>
<!ATTLIST item %coreattrs;>

<!ELEMENT table (caption?,tr+)>
<!ATTLIST table %coreattrs;>

<!ELEMENT tr (td)+>
<!ATTLIST tr %coreattrs;>

<!ELEMENT td (%flow;)*>
<!ATTLIST td %coreattrs;>

<!ELEMENT caption (%inline;)*>
<!ATTLIST caption %coreattrs;>

<!-- ]> -->

=== mame/xmlparser/samples/index_noenc.xml
<!DOCTYPE document SYSTEM "document.dtd">

<document>
  <title>よしだむの秘密のページ</title>

  <para>
  よしだむの秘密のページにようこそ☆
  </para>
  <para>
  このページは HTML4.0，CSS 1.0 に準拠した Web ブラウザで閲覧することを
  お勧めします。
  </para>

  <index>
    <link xml:link="simple" href="/">[bekkoame ホームページ]</link>
  </index>


  <section>
    <heading>更新情報</heading>
    <subsection>
      <heading>1998/07/08</heading>
      <list>
        <item>XML2HTML でページを生成するようにしました</item>
        <item>Ruby ページで XMLParser モジュールと Uconv モジュールの公開
        を始めました</item>
      </list>
    </subsection>
  </section>


  <section id="hobby">
    <heading>趣味</heading>
   <subsection id="ruby">
      <heading><link xml:link="simple" href="Ruby.html">♪Ruby</link></heading>
      <para>最近は Ruby なのです。</para>
    </subsection>

    <subsection id="xml">
      <heading><link xml:link="simple" href="XML.html">♪XML</link></heading>
      <para>XML もやってます。</para>
      <list>
        <item>
          <link xml:link="simple" href="index.xml">このページのソース 
            (XML)</link>
        </item>
        <item>
          <link xml:link="simple" href="document.dtd">このページの DTD</link>
        </item>
        <item>
          <link xml:link="simple" href="document.css">このページのスタイル
          シート</link>
        </item>
      </list>
    </subsection>
  </section>

  <section id="misc">
    <heading>その他のページ</heading>
    <list>
      <item><link xml:link="simple" href="http://www.cipuco.net/">
	CIPUCO!!</link></item>
    </list>
  </section>

  <rpara>
      Copyright 1998 by
	<link xml:link="simple" href="mailto:yoshidam@yoshidam.net">
	  Yoshida Masato (yoshidam@yoshidam.net)</link>
  </rpara>
</document>
